# Generated by Django 4.2.23 on 2025-10-13 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=100)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('avg_rating', models.FloatField(blank=True, null=True)),
                ('is_5g', models.BooleanField(default=False)),
                ('processor_brand', models.CharField(blank=True, max_length=50, null=True)),
                ('num_cores', models.IntegerField(blank=True, null=True)),
                ('processor_speed', models.FloatField(blank=True, help_text='in GHz', null=True)),
                ('battery_capacity', models.IntegerField(blank=True, help_text='in mAh', null=True)),
                ('fast_charging_available', models.BooleanField(default=False)),
                ('fast_charging', models.CharField(blank=True, max_length=50, null=True)),
                ('ram_capacity', models.IntegerField(blank=True, help_text='in GB', null=True)),
                ('internal_memory', models.IntegerField(blank=True, help_text='in GB', null=True)),
                ('extended_memory_available', models.BooleanField(default=False)),
                ('screen_size', models.FloatField(blank=True, help_text='in inches', null=True)),
                ('refresh_rate', models.IntegerField(blank=True, help_text='in Hz', null=True)),
                ('resolution_height', models.IntegerField(blank=True, null=True)),
                ('resolution_width', models.IntegerField(blank=True, null=True)),
                ('num_rear_cameras', models.IntegerField(blank=True, null=True)),
                ('primary_camera_rear', models.IntegerField(blank=True, null=True)),
                ('primary_camera_front', models.IntegerField(blank=True, null=True)),
                ('os', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
